### ISSUE TITLE
请问--ip <string> 是否支持同时配置IPv4，IPv6

### ISSUE THREAD

**Issue by jhcn** [bohanyang/debi#130]
其正确语法是怎样，多谢

**Comment by bohanyang** [comment]
亲 --ip 不支持同时配置IPv4，IPv6呢。这是因为 Debian 安装程序本身不支持呢。
可以通过 cloud-init 配置安装后的网络。

`--cidata  ./cidata-example` https://github.com/bohanyang/debi/tree/master/cidata-example

在这个目录里面加上 network-config 文件，内容如下。然后通过以上选项指定目录。

甲骨文（DHCP自动配置双栈）
```
version: 1
config:
  - type: physical
    accept-ra: true
    name: eth0
    mac_address: "aa:aa:aa:aa:aa:aa"
    subnets:
      - type: dhcp

```

静态IP
```
version: 1
config:
  - type: physical
    accept-ra: false
    name: eth0
    mac_address: "aa:aa:aa:aa:aa:aa"
    subnets:
      - type: static
        address: "1.1.1.227/23"
        gateway: "1.1.1.1"
      - type: static6
        address: "2000:a:a:a::a/56"
        gateway: "2000:a:a:a::1"
  - type: nameserver
    address: ["8.8.8.8"]
```
